# Generated by Django 6.0 on 2025-12-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_category_options_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/%Y%m%d"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
