# Generated by Django 6.0 on 2025-12-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_alter_blog_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_body",
            field=models.TextField(max_length=5000),
        ),
    ]
