# Generated by Django 6.0 on 2026-01-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0008_aboutus_socialmedia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutus",
            options={"ordering": ["-created_at"], "verbose_name_plural": "About Us"},
        ),
        migrations.AlterModelOptions(
            name="socialmedia",
            options={"verbose_name_plural": "Social Media"},
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="link",
            field=models.URLField(max_length=100),
        ),
    ]
