# Generated by Django 6.0 on 2026-01-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0011_alter_aboutus_id_alter_blog_id_alter_blog_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
