# Generated by Django 6.0 on 2026-01-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0013_comments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comments",
            options={"verbose_name_plural": "Comments"},
        ),
    ]
